### PR TITLE
Add event node

### PR DESCRIPTION
**Pull request by lopelex**
@BrokenThings.
Added an event node. Thus you get back status and the events of miio. 
Hope you like it.

### CODE REVIEW

**Comment by MickL** [comment]
Thats awesome! @BrokenThings could you please review and merge?

**Comment by andreypopov** [comment]
merge pls)

**Comment by BrokenThings** [comment]
Nice. Thanks for contributing.

**Comment by lopelex** [comment]
@BrokenThings:
I noticed that the connection to the vacuum cleaner is disconnected after some time.  
Have tested a bit how to maintain the connection or reconnect.
https://github.com/lopelex/node-red-contrib-xiaomi-roborock/tree/socket

**Comment by andreypopov** [comment]
Ok, I forked this repo, but then created new repo.
https://github.com/andreypopov/node-red-contrib-miio-roborock

Possible fixed connection errors. testing


It is early version, but I will develop stable in next 30 days

**Comment by andreypopov** [comment]
> @BrokenThings:
> I noticed that the connection to the vacuum cleaner is disconnected after some time.
> Have tested a bit how to maintain the connection or reconnect.
> https://github.com/lopelex/node-red-contrib-xiaomi-roborock/tree/socket

every event node has separate connect - not good. It has to be inside controller node. One connect per one device.

**Pull request merged**
